### PR TITLE
add padding to align usbif_response_t on 64 bits

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-428

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
After working on the Windows front end I realized that the usbif header was changed quite a bit from the original xen one. Since there is no current issue with Windows 32 vs. 64 bits I am going to close this and not monkey with working stuffs.

**Comment by rossphilipson** [comment]
This related to: https://openxt.atlassian.net/browse/OXT-428

I tested and adding the padding does not change the struct size on either 32 or 64. I suggest we reopen and merge this. It is more correct to have all the structs match. I was able to reopen this one.

**Comment by rossphilipson** [comment]
Actually hold on. These are the wrong structs to pad. Something is wrong here - need to talk to Jed.

**Comment by jean-edouard** [comment]
Title and comment fixed, this should be good to go.

**Comment by rossphilipson** [comment]
+1 - I have tested these changes with numerous devices on 32/64b Windows so it is happy. I also sanity checked that adding the pad does not change the struct sizes. I am just waiting for the other PR because they should go in together.

**Pull request merged**
